### ISSUE TITLE
Cannot compile Lottie for iOS

### ISSUE THREAD

**Issue by mergesort** [airbnb/lottie-ios#607]
## Check these before submitting:
- [x] Updated to the latest version of Lottie (2.5.0)
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [x] Regression (Something that once worked, but doesn't work anymore)

## What Platform are you on? 

- [] MacOS
- [x] iOS

## Expected Behavior 
I expect Lottie to be able to compile in a project using Swift 4.1, CocoaPods 1.5, and Lottie 2.5.0.

## Actual Behavior
Lottie does not compile in my project. I've tried rebuilding, clearing derived data, and even restarting. I upgraded from Lottie 2.1.3, and that was working fine, but now I cannot get it to compile. The file appears on the file system, but does not seem to be getting compiled into the project generated by CocoaPods.

<img width="603" alt="compilation error" src="https://user-images.githubusercontent.com/716513/38838460-25eb92e6-41a4-11e8-999b-a15d2bb2d4ae.png">

## Code Example
N/A

**Comment by mergesort** [comment]
Closing this out. It turned out this was an issue with another framework when compiling in Xcode 9.3. Sorry about that. 🙇
